const test=require('node:test'),assert=require('node:assert/strict');
const {begin}=require('../src/secretary-setup.cjs');
const {handleHelperEdit}=require('../src/helper-edit.cjs');
const {syncDraft,resolveConflict,draftReminderDue}=require('../src/draft-sync.cjs');
const {memberProjection}=require('../src/helper-members.cjs');
const target={name:'Test_group',groupId:'123@g.us',testOnly:true};
function ready(){const s=begin(Date.parse('2026-10-07T12:00:00Z'));Object.assign(s,{stage:'complete',groupLink:{connected:true},helperGroupPost:{status:'sent'},postingTime:'8:10 PM',memberLive:{board:structuredClone(s.board),windowEnd:Date.parse('2026-10-09T14:40:00Z')}});return handleHelperEdit(s,{id:'edit',text:'EDIT'},target).state;}
const role=(b,r)=>b.find(x=>x.role===r);
test('member updates remain approved while a private draft is open',()=>{assert.equal(memberProjection(ready(),target,{}).status,'approved');});
test('draft stores its starting board and merges untouched newer roles',()=>{const s=ready();assert.deepEqual(s.memberEdit.baseBoard,s.memberLive.board);role(s.memberEdit.board,'Timer').member='Priya Example';role(s.memberLive.board,'Listener').member='Aman Example';assert.equal(syncDraft(s).changed,true);assert.equal(role(s.memberEdit.board,'Listener').member,'Aman Example');assert.equal(role(s.memberEdit.board,'Timer').member,'Priya Example');assert.deepEqual(s.memberEdit.conflicts,[]);});
test('same-role conflicts require a choice, a fresh preview and approval',()=>{let s=ready();role(s.memberEdit.board,'Timer').member='Priya Example';role(s.memberLive.board,'Timer').member='Aman Example';s.memberEdit.stage='preview';s.memberEdit.previewAcknowledged=true;s.memberEdit.previewReceipt={id:'old'};s=handleHelperEdit(s,{id:'approve',text:'APPROVE'},target).state;assert.notEqual(s.memberEdit.stage,'post_ready');assert.match(s.outbox.at(-1).text,/KEEP CURRENT/);s=handleHelperEdit(s,{id:'keep',text:'KEEP CURRENT'},target).state;assert.equal(role(s.memberEdit.board,'Timer').member,'Aman Example');assert.equal(s.memberEdit.previewAcknowledged,false);assert.equal(s.outbox.at(-1).kind,'edit-preview');});
test('choosing the draft cannot authorize a later conflicting member change',()=>{const s=ready();role(s.memberEdit.board,'Timer').member='Priya Example';role(s.memberLive.board,'Timer').member='Aman Example';syncDraft(s);assert.equal(resolveConflict(s,'USE DRAFT'),true);assert.equal(s.memberEdit.conflicts.length,0);role(s.memberLive.board,'Timer').member='Noah Example';syncDraft(s);assert.equal(s.memberEdit.conflicts.length,1);});
test('draft reminder is one hour before club time, once per day, within meeting cutoff',()=>{const s=ready();assert.equal(draftReminderDue(s,Date.parse('2026-10-07T13:39:59Z')),null);const due=draftReminderDue(s,Date.parse('2026-10-07T13:40:00Z'));assert.equal(due,'2026-10-07T14:40:00.000Z');s.memberEdit.remindedAt=due;assert.equal(draftReminderDue(JSON.parse(JSON.stringify(s)),Date.parse('2026-10-07T14:00:00Z')),null);assert.equal(draftReminderDue(s,Date.parse('2026-10-07T14:40:00Z')),null);assert.equal(draftReminderDue(s,Date.parse('2026-10-08T13:40:00Z')),'2026-10-08T14:40:00.000Z');assert.equal(draftReminderDue(s,Date.parse('2026-10-10T13:40:00Z')),null);});
test('multiple conflicts resolve one at a time and persist across restart',()=>{let s=ready();for(const r of ['Timer','Listener']){role(s.memberEdit.board,r).member=r==='Timer'?'Priya Example':'Lena Example';role(s.memberLive.board,r).member=r==='Timer'?'Aman Example':'Noah Example';}syncDraft(s);assert.equal(s.memberEdit.conflicts.length,2);s=JSON.parse(JSON.stringify(s));resolveConflict(s,'KEEP CURRENT');assert.equal(s.memberEdit.conflicts.length,1);assert.equal(role(s.memberEdit.board,'Timer').member,'Aman Example');resolveConflict(s,'USE DRAFT');assert.equal(s.memberEdit.conflicts.length,0);assert.equal(role(s.memberEdit.board,'Listener').member,'Lena Example');assert.equal(s.memberEdit.previewAcknowledged,false);});
test('a legacy draft preserves uncertain edits and asks before replacing a newer holder',()=>{const s=ready();delete s.memberEdit.baseBoard;role(s.memberEdit.board,'Timer').member='Priya Example';role(s.memberLive.board,'Timer').member='Aman Example';assert.equal(syncDraft(s).conflicts.length,1);assert.equal(role(s.memberEdit.board,'Timer').member,'Priya Example');});
test('new member assignment to another role cannot make the Secretary approve duplicate holders',()=>{let s=ready();role(s.memberEdit.board,'Timer').member='Priya Example';role(s.memberLive.board,'Listener').member='Priya Example';s.memberEdit.stage='preview';s.memberEdit.previewAcknowledged=true;s.memberEdit.previewReceipt={id:'old'};s=handleHelperEdit(s,{id:'duplicate',text:'APPROVE'},target).state;assert.notEqual(s.memberEdit.stage,'post_ready');assert.match(s.outbox.at(-1).text,/choose one role/);});
