const test=require('node:test'),assert=require('node:assert/strict'),{createHash}=require('node:crypto');
const {begin,applySetup}=require('../src/secretary-setup.cjs');
const {handleHelperEdit,deliverHelperCorrection}=require('../src/helper-edit.cjs');
const {syncDraft}=require('../src/draft-sync.cjs');
const {draftReminderDue}=require('../src/draft-sync.cjs');
const now=Date.parse('2026-10-11T05:00:00Z'),target={name:'CHD TM',groupId:'123@g.us',testOnly:true};
function ready(){const s=begin(now,{pilotMode:true});Object.assign(s,{stage:'complete',meetingDayIndex:6,meetingDay:'Saturday',postingTime:'8:00 PM',approvedHash:'old',groupLink:{connected:true,groupId:target.groupId},helperGroupPost:{status:'sent',id:'old',sha256:'old',serverAckVerified:true},memberTest:{authorized:true,done:false,dueAt:'old'}});Object.assign(s.meeting,{date:'10 October 2026',number:'42',venue:'Cedar Hall'});s.board.find(r=>r.role==='Timer').member='Mira Example';s.board.find(r=>r.role==='Timer').memberId='old-account';s.memberLive={board:structuredClone(s.board),publishedBoard:structuredClone(s.board),posts:{old:{status:'sent'}},inbox:[{id:'old-message'}],seen:['old-message'],startedAt:now-86400000,windowEnd:now-1000,authorization:{initialApprovedHash:'old'},dirty:false};return s;}
function start(s=ready()){return applySetup(s,{id:'fresh',text:'START'},now,{pilotMode:true});}
test('START after completed setup creates an open-role draft and keeps the approved board intact',()=>{const old=ready(),s=start(old);assert.ok(s.memberEdit);assert.equal(s.memberEdit.kind,'new_meeting');assert.ok(s.memberEdit.board.every(r=>r.member===null&&!r.memberId&&!r.memberIds));assert.equal(s.memberEdit.meeting.date,'17 October 2026');assert.equal(s.memberEdit.meeting.number,'43');assert.equal(s.memberEdit.meeting.venue,'Cedar Hall');for(const field of ['board','meeting','groupLink','helperGroupPost','memberLive','reminder','postingTime'])assert.deepEqual(s[field],old[field]);assert.equal(s.outbox.at(-1).kind,'edit-preview');});
test('TABLE uses the new draft and cannot bring back the previous role holders',()=>{let s=start();syncDraft(s);s=handleHelperEdit(s,{id:'table',text:'TABLE'},target,now).state;assert.ok(s.memberEdit.board.every(r=>r.member===null));assert.doesNotMatch(s.outbox.findLast(i=>i.kind==='text').text,/Mira Example/);assert.equal(s.memberLive.board.find(r=>r.role==='Timer').member,'Mira Example');});
test('repeated START resumes the existing fresh draft without clearing corrections',()=>{let s=start();s=handleHelperEdit(s,{id:'fill',text:'Timer: Ada Example'},target,now).state;s=handleHelperEdit(s,{id:'again',text:'START'},target,now).state;assert.equal(s.memberEdit.board.find(r=>r.role==='Timer').member,'Ada Example');assert.equal(s.memberEdit.meeting.number,'43');});
test('CANCEL discards only the new draft, preserving the posted board and receipts',()=>{const old=ready(),s=handleHelperEdit(start(old),{id:'cancel',text:'CANCEL'},target,now).state;assert.equal(s.memberEdit,null);for(const field of ['board','meeting','groupLink','helperGroupPost','memberLive'])assert.deepEqual(s[field],old[field]);});
test('restart and duplicate START preserve the new draft without duplicate sends',()=>{const s=start(),restored=JSON.parse(JSON.stringify(s));assert.deepEqual(applySetup(restored,{id:'fresh',text:'START'},now,{pilotMode:true}),s);assert.ok(restored.memberEdit.board.every(r=>r.member===null));});
test('an existing correction draft is preserved when START is sent',()=>{let s=handleHelperEdit(ready(),{id:'edit',text:'EDIT'},target,now).state;s=handleHelperEdit(s,{id:'role',text:'Listener: Ada Example'},target,now).state;const board=structuredClone(s.memberEdit.board);s=handleHelperEdit(s,{id:'start',text:'START'},target,now).state;assert.deepEqual(s.memberEdit.board,board);assert.notEqual(s.memberEdit.kind,'new_meeting');});
test('fresh draft reminders use the new date even when the previous posting window has closed',()=>{const s=start();assert.equal(draftReminderDue(s,Date.parse('2026-10-11T13:30:00Z')),'2026-10-11T14:30:00.000Z');assert.equal(s.memberLive.windowEnd,now-1000);});
test('fresh board delivery archives the old cycle and starts member listening without old queued claims',async()=>{let s=start();s=handleHelperEdit(s,{id:'fill',text:'Timer: Ada Example'},target,now).state;s.memberEdit.previewAcknowledged=true;s.memberEdit.previewReceipt={id:'fresh-preview',sha256:s.memberEdit.boardHash};s=handleHelperEdit(s,{id:'approve',text:'APPROVE'},target,now).state;const identity={secretaryId:'111@s.whatsapp.net'},helper={secretaryId:'222@s.whatsapp.net'};let sends=0;assert.equal(await deliverHelperCorrection({state:s,target,identity,helper,socket:{groupMetadata:async()=>({id:target.groupId,subject:target.name,participants:[{id:identity.secretaryId},{id:helper.secretaryId}]})},save:async()=>{},now,acknowledgements:{wait:async()=>{}},sendImage:async(_s,_t,png)=>{sends++;return {id:'new-post',sha256:createHash('sha256').update(png).digest('hex')};}}),true);assert.equal(sends,1);assert.equal(s.memberEdit,null);assert.equal(s.memberLive.board.find(r=>r.role==='Timer').member,'Ada Example');assert.deepEqual(s.memberLive.inbox,[]);assert.deepEqual(s.memberLive.posts,{});assert.equal(s.memberLive.startedAt,now);assert.equal(s.memberListeningStartedAt,now);assert.equal(s.previousMeetings[0].memberLive.inbox[0].id,'old-message');assert.equal(s.memberTest,undefined);});
