const {test}=require('node:test');const assert=require('node:assert/strict');const {createHash}=require('node:crypto');
const {deliverPreviewOnce}=require('../src/preview-outbox.cjs');const {renderBoardImage}=require('../src/board-image.cjs');const fixture=require('./fixtures/milestone-3.cjs');
const secretaryId='15550000001@s.whatsapp.net';
function setup(){const png=renderBoardImage(fixture).png;const state={boardHash:createHash('sha256').update(png).digest('hex'),ownIds:[]};let sends=0,acks=0;
 const socket={sendMessage:async(destination,payload)=>{sends++;return {key:{id:'fictional-preview-'+sends,remoteJid:destination,fromMe:true},message:{imageMessage:{caption:payload.caption,width:payload.width,height:payload.height,jpegThumbnail:payload.jpegThumbnail,fileSha256:createHash('sha256').update(payload.image).digest()}}};}};
 return {state,item:{},socket,secretaryId,png,caption:'Fictional preview',save:async()=>{},acknowledgements:{wait:async()=>{acks++;}},counts:()=>({sends,acks})};}
test('identical queued previews with different wording send one image',async()=>{const input=setup();await deliverPreviewOnce(input);await deliverPreviewOnce({...input,item:{},caption:'Updated wording'});assert.deepEqual(input.counts(),{sends:1,acks:1});});
test('a saved acknowledged preview is reused after restarting',async()=>{const input=setup();await deliverPreviewOnce(input);const state=JSON.parse(JSON.stringify(input.state));await deliverPreviewOnce({...input,state,item:{}});assert.equal(input.counts().sends,1);});
test('a previous-version preview receipt prevents another identical image',async()=>{const input=setup();input.state.previewReceipt={id:'fictional-existing',sha256:input.state.boardHash};input.state.lastPreviewServerAckVerified=true;await deliverPreviewOnce(input);assert.deepEqual(input.counts(),{sends:0,acks:0});});
test('missing acknowledgement retries the existing receipt without sending again',async()=>{const input=setup();const ack=input.acknowledgements;input.acknowledgements={wait:async()=>{throw Error('Missing receipt');}};await assert.rejects(deliverPreviewOnce(input),/Missing receipt/);await deliverPreviewOnce({...input,acknowledgements:ack});assert.equal(input.counts().sends,1);});
test('an uncertain attempt without a receipt cannot be duplicated',async()=>{const input=setup();input.state.previewDeliveries={[input.state.boardHash]:{status:'sending'}};await assert.rejects(deliverPreviewOnce(input),/uncertain/);assert.equal(input.counts().sends,0);});
test('a changed board receives exactly one new preview',async()=>{const input=setup();await deliverPreviewOnce(input);const other=structuredClone(fixture);other.meeting.number='43';const png=renderBoardImage(other).png;input.state.boardHash=createHash('sha256').update(png).digest('hex');await deliverPreviewOnce({...input,png,item:{}});assert.equal(input.counts().sends,2);});
