const test=require('node:test'),assert=require('node:assert/strict'),{createHash}=require('node:crypto');
const {begin}=require('../src/secretary-setup.cjs');
const {createClubEngine}=require('../src/club-engine.cjs');
const {translateSecretary}=require('../src/secretary-language.cjs');
const now=Date.parse('2026-10-11T05:00:00Z');
const set=(role,member)=>({operation:'set',role,member});
const batch=(edits,question)=>({action:'edits',confidence:1,edits,...(question?{question}:{})});
function fixture(decision){const s=begin(now,{pilotMode:true});s.stage='complete';s.groupHelpSent=true;const club={id:'example',identity:{secretaryId:'111@s.whatsapp.net'},state:s,target:null},sent=[];let calls=0;const engine=createClubEngine({club,registry:{version:2,clubs:[club]},pilotMode:true,now:()=>now,interpretSecretary:async()=>{calls++;return {decision};},save:async()=>{},acknowledgements:{wait:async()=>{}},socket:{sendMessage:async(jid,content)=>{sent.push({jid,content});return {key:{id:'text-'+sent.length,remoteJid:jid,fromMe:true}};}},sendPreview:async(_s,jid,png)=>{sent.push({jid,png});return {id:'preview-'+sent.length,sha256:createHash('sha256').update(png).digest('hex')};}});return {club,sent,engine,calls:()=>calls};}
test('two clear natural role assignments give one summary and one private preview',async()=>{const f=fixture(batch([set('Speaker 1','Ada Example'),set('Timer','Mira Example')]));await f.engine.command({id:'two',text:'set Speaker 1 to Ada Example and Timer to Mira Example'});const d=f.club.state.memberEdit;assert.equal(d.board.find(r=>r.role==='Speaker 1').member,'Ada Example');assert.equal(d.board.find(r=>r.role==='Timer').member,'Mira Example');assert.ok(f.club.state.board.every(r=>r.member===null));assert.equal(f.sent.filter(s=>s.png).length,1);assert.equal(f.sent.filter(s=>s.content?.text).length,1);assert.match(f.sent[0].content.text,/Draft updated:[\s\S]*Speaker 1 — Ada Example[\s\S]*Timer — Mira Example/);assert.ok(f.sent.every(s=>s.jid===f.club.identity.secretaryId));});
test('exact batches with WhatsApp formatting bypass the AI and retain both edits',async()=>{for(const text of ['`Speaker 1: Ada Example; Timer: Mira Example`','*Speaker 1: Ada Example; Timer: Mira Example*','Speaker 1: Ada Example\nTimer: Mira Example\n']){const f=fixture({action:'clarify',confidence:1,question:'Which change first?'});await f.engine.command({id:'exact',text});assert.equal(f.calls(),0);assert.equal(f.club.state.memberEdit.board.find(r=>r.role==='Timer').member,'Mira Example');assert.equal(f.sent.length,2);}});
test('clear assignments apply while only an unclear remaining role gets a question',async()=>{const f=fixture(batch([set('Timer','Mira Example')],'Who should hold Listener?'));await f.engine.command({id:'partial',text:'set Timer to Mira Example and change Listener'});assert.equal(f.club.state.memberEdit.board.find(r=>r.role==='Timer').member,'Mira Example');assert.equal(f.sent.filter(s=>s.png).length,1);assert.equal(f.sent.at(-1).content.text,'Who should hold Listener?');});
test('clear assignments apply but occupied-role replacement waits for private confirmation',async()=>{const f=fixture(batch([set('Speaker 1','Ada Example'),set('Timer','Mira Example')]));f.club.state.board.find(r=>r.role==='Timer').member='Noah Example';await f.engine.command({id:'mixed',text:'set Speaker 1 to Ada Example and Timer to Mira Example'});assert.equal(f.club.state.memberEdit.board.find(r=>r.role==='Speaker 1').member,'Ada Example');assert.equal(f.club.state.memberEdit.board.find(r=>r.role==='Timer').member,'Noah Example');assert.match(f.sent.at(-1).content.text,/replacing Noah Example/);await f.engine.command({id:'yes',text:'yes'});assert.equal(f.club.state.memberEdit.board.find(r=>r.role==='Timer').member,'Mira Example');assert.equal(f.club.state.board.find(r=>r.role==='Timer').member,'Noah Example');});
test('multiple replacements are confirmed one at a time and survive restart',async()=>{const f=fixture(batch([set('Timer','Mira Example'),set('Listener','Ada Example')]));f.club.state.board.find(r=>r.role==='Timer').member='Noah Example';f.club.state.board.find(r=>r.role==='Listener').member='Lena Example';await f.engine.command({id:'swap',text:'set Timer to Mira Example and Listener to Ada Example'});assert.match(f.sent.at(-1).content.text,/Timer/);assert.doesNotMatch(f.sent.at(-1).content.text,/Listener/);f.club.state=JSON.parse(JSON.stringify(f.club.state));await f.engine.command({id:'yes1',text:'yes'});assert.match(f.sent.at(-1).content.text,/Listener/);await f.engine.command({id:'yes2',text:'yes'});assert.equal(f.club.state.memberEdit.board.find(r=>r.role==='Listener').member,'Ada Example');assert.equal(f.club.state.secretaryQuestion,undefined);});
test('fabricated names, conflicting assignments and duplicate holders do not change roles',async()=>{for(const edits of [[set('Timer','Invented Person')],[set('Timer','Ada Example'),set('Timer','Mira Example')],[set('Timer','Ada Example'),set('Listener','Ada Example')]]){const f=fixture(batch(edits));await f.engine.command({id:'invalid',text:'set Timer to Ada Example and Listener to Mira Example'});assert.equal(f.club.state.memberEdit,undefined);assert.ok(f.club.state.board.every(r=>r.member===null));assert.equal(f.sent.filter(s=>s.png).length,0);}});
test('a changed saved board invalidates a pending batch replacement',async()=>{const s=begin(now,{pilotMode:true});s.stage='complete';s.board.find(r=>r.role==='Timer').member='Noah Example';const result=await translateSecretary(s,{id:'swap',text:'set Timer to Mira Example'},async()=>({decision:batch([set('Timer','Mira Example')])}));s.secretaryQuestion=result.pending;s.board.find(r=>r.role==='Timer').member='Lena Example';const confirmed=await translateSecretary(s,{id:'yes',text:'yes'},async()=>({decision:{action:'command',command:'APPROVE',confidence:1}}));assert.match(confirmed.question,/board has changed/);assert.equal(confirmed.text,undefined);});
