import { v } from 'convex/values';
const nullable=v.union(v.string(),v.null());
export const role=v.object({role:v.string(),member:nullable});
export const meeting=v.object({club:nullable,number:nullable,date:nullable,time:nullable,venue:nullable});
export const activity=v.object({trackingSince:v.number(),complete:v.boolean(),secretaryActive:v.boolean(),clubActive:v.boolean(),lastSecretaryAt:v.union(v.number(),v.null()),lastClubAt:v.union(v.number(),v.null()),secretaryMessages:v.number(),memberReplies:v.number(),roleUpdates:v.number(),boardsApproved:v.number(),boardsPosted:v.number(),deliveryFailures:v.number(),setupsCompleted:v.number()});
export const health=v.object({service:v.union(v.object({connected:v.boolean(),lastCheckAt:v.number(),startedAt:v.number(),controlsCheckedAt:v.optional(v.union(v.number(),v.null()))}),v.null()),ai:v.union(v.object({callsLastHour:v.number(),callLimit:v.number(),reservedUsd:v.number(),budgetLimitUsd:v.number()}),v.null())});
export const control=v.object({token:v.string(),pausedAt:nullable,pauseReason:nullable,resumeBlocked:nullable});
export const actionKind=v.union(v.literal('pause'),v.literal('resume'));
export const actionStatus=v.union(v.literal('pending'),v.literal('succeeded'),v.literal('failed'));
export const actionView=v.object({id:v.id('adminActions'),clubId:v.string(),club:v.string(),kind:actionKind,requestedAt:v.number(),completedAt:v.union(v.number(),v.null()),status:actionStatus,message:nullable});
export const account=v.object({control:v.optional(control),activity:v.optional(v.union(activity,v.null())),id:v.string(),club:v.string(),secretary:v.string(),group:nullable,connected:v.boolean(),paused:v.boolean(),stage:v.string(),postingTime:nullable,nextUpdate:nullable,meeting,approved:v.array(role),current:v.array(role),draft:v.union(v.object({stage:v.string(),meeting,roles:v.array(role)}),v.null()),deliveries:v.array(v.object({status:v.string(),postedAt:nullable,acknowledged:v.boolean()})),needsAttention:v.boolean()});
export const snapshot=v.object({health:v.optional(health),capturedAt:v.number(),accounts:v.array(account)});
