import React,{useState,useEffect} from 'react';
import {createRoot} from 'react-dom/client';
import {ConvexReactClient,useQuery,useConvexAuth} from 'convex/react';
import {ConvexAuthProvider,useAuthActions} from '@convex-dev/auth/react';
import {api} from '../convex/_generated/api';
const client=new ConvexReactClient(__ADMIN_CONVEX_URL__);
const date=v=>v?new Intl.DateTimeFormat('en-IN',{dateStyle:'medium',timeStyle:'short',timeZone:'Asia/Kolkata'}).format(new Date(v)):'Not recorded';
function Brand(){return <a className="brand" href="/">the helper<span>.</span></a>;}
function Login(){const {signIn}=useAuthActions(),[busy,setBusy]=useState(false),[error,setError]=useState(location.search.includes('error=')?'Sign-in was not completed. Use the approved owner account and try again.':'');return <main className="login"><Brand/><div className="login-body"><h1>Your clubs.<br/>One clear view.</h1><p>Check Secretary accounts, meeting boards and posting status in your private owner panel.</p><button disabled={busy} onClick={async()=>{setBusy(true);setError('');try{await signIn('google',{redirectTo:'/admin.html'});}catch{setError('Google sign-in could not start. Try again once owner login is configured.');setBusy(false);}}}>{busy?'Opening Google…':'Sign in with Google'}</button>{error&&<p role="alert" className="error">{error}</p>}<p className="quiet">Owner access only. Secretary conversations are not shown here.</p></div><a href="/">Back to the helper</a></main>;}
class Boundary extends React.Component{constructor(p){super(p);this.state={failed:false};}static getDerivedStateFromError(){return {failed:true};}render(){return this.state.failed?<main className="failure"><h1>This view is unavailable</h1><p>Your account may not have owner access, or the connection was interrupted. No club settings were changed.</p><button onClick={()=>location.reload()}>Try again</button><Exit/></main>:this.props.children;}}
function Exit(){const {signOut}=useAuthActions();return <button className="secondary" onClick={()=>signOut()}>Sign out</button>;}
function Roles({rows}){return rows.length?<div className="table-scroll"><table><thead><tr><th scope="col">Role</th><th scope="col">Holder</th></tr></thead><tbody>{rows.map(r=><tr key={r.role}><td>{r.role}</td><td className={!r.member?'quiet':''}>{r.member||'Open'}</td></tr>)}</tbody></table></div>:<p className="quiet">No board saved yet.</p>;}
function Details({account:a}){const [tab,setTab]=useState('current');useEffect(()=>setTab('current'),[a.id]);const shown=tab==='draft'?a.draft?.roles||[]:a[tab],m=tab==='draft'?a.draft?.meeting||a.meeting:a.meeting;return <section className="details" aria-label="Account details"><h2>{a.club}</h2><p className="quiet">Secretary +{a.secretary} · {a.group||'Group not connected'}</p><dl className="settings"><div><dt>Meeting</dt><dd>{m.number||'Not set'} · {m.date||'Date not set'}</dd></div><div><dt>Time and venue</dt><dd>{m.time||'Not set'} · {m.venue||'Venue not set'}</dd></div><div><dt>Board updates</dt><dd>{a.postingTime||'Not set'} India time</dd></div><div><dt>Next pending update</dt><dd>{a.nextUpdate?date(a.nextUpdate):'No pending update'}</dd></div></dl><div className="board-tabs" aria-label="Choose a board">{[['current','Current roles'],['approved','Approved board'],['draft','Private draft']].map(([id,label])=><button className={tab===id?'selected':'secondary'} aria-pressed={tab===id} key={id} onClick={()=>setTab(id)}>{label}</button>)}</div><p className="board-note">{tab==='current'?'Latest saved roles, including confirmed member replies. Changes may still be awaiting approval or posting.':tab==='approved'?'The Secretary-approved board. Later member updates are shown under Current roles.':'Unapproved changes stay private until the Secretary approves.'}</p><Roles rows={shown}/><h3>Recent delivery records</h3>{a.deliveries.length?<ul className="deliveries">{a.deliveries.slice().reverse().map((p,i)=><li key={i}><span>{p.status} · {p.acknowledged?'Delivery confirmed':'Delivery not confirmed'}</span><time>{date(p.postedAt)}</time></li>)}</ul>:<p className="quiet">No saved delivery records.</p>}</section>;}
function Overview(){const data=useQuery(api.admin.overview),[search,setSearch]=useState(''),[selected,setSelected]=useState(null),[now,setNow]=useState(Date.now());useEffect(()=>{const timer=setInterval(()=>setNow(Date.now()),30000);return ()=>clearInterval(timer);},[]);if(!data)return <main className="loading" role="status">Loading your Secretary accounts…</main>;const filtered=data.accounts.filter(a=>(a.club+' '+a.secretary+' '+(a.group||'')).toLowerCase().includes(search.toLowerCase()));const account=data.accounts.find(a=>a.id===selected);const stale=!data.capturedAt||now-data.capturedAt>180000;return <><header><Brand/><Exit/></header><main className="overview"><div className="heading"><div><h1>Secretary overview</h1><p>Check your clubs and the boards they are working on.</p></div><span className="read-only">Read-only view</span></div><p className={stale?'freshness stale':'freshness'} role="status">{data.capturedAt?`${stale?'Update delayed':'Last updated'}: ${date(data.capturedAt)} India time`:'Waiting for the first helper update. No account data has arrived yet.'}</p><dl className="counts">{[['Secretaries',data.count],['Connected clubs',data.connected],['Paused',data.paused],['Need attention',data.attention]].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{data.capturedAt?value:'—'}</dd></div>)}</dl><p className="quiet">Activity in the last seven days will appear when activity tracking is added.</p><label className="search">Find a Secretary or club<input type="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Club name or WhatsApp number"/></label><div className="workspace"><section aria-label="Secretary accounts" className="accounts">{filtered.length?filtered.map(a=><button className={'account '+(selected===a.id?'active':'')} key={a.id} onClick={()=>setSelected(a.id)}><span><strong>{a.club}</strong><small>+{a.secretary}</small></span><span className="status">{a.paused?'Paused':a.connected?'Connected':'Setup: '+a.stage.replaceAll('_',' ')}</span></button>):<p className="empty">{search?'No accounts match your search.':'No Secretary accounts yet.'}</p>}</section>{account?<Details account={account}/>:<section className="details empty"><h2>Select a club</h2><p>View its settings, all saved roles and recent delivery records.</p></section>}</div></main></>;}
function App(){const {isLoading,isAuthenticated}=useConvexAuth();return isLoading?<main className="loading" role="status">Checking your sign-in…</main>:isAuthenticated?<Boundary><Overview/></Boundary>:<Login/>;}
createRoot(document.getElementById('root')).render(<ConvexAuthProvider client={client}><App/></ConvexAuthProvider>);
