import React,{useState,useEffect} from 'react';
import {createRoot} from 'react-dom/client';
import {ConvexReactClient,useQuery,useMutation,useConvexAuth} from 'convex/react';
import {ConvexAuthProvider,useAuthActions} from '@convex-dev/auth/react';
import {api} from '../convex/_generated/api';
const client=new ConvexReactClient(__ADMIN_CONVEX_URL__);
const date=v=>v?new Intl.DateTimeFormat('en-IN',{dateStyle:'medium',timeStyle:'short',timeZone:'Asia/Kolkata'}).format(new Date(v)):'Not recorded';
function Brand(){return <a className="brand" href="/">the helper<span>.</span></a>;}
function Login(){const {signIn}=useAuthActions(),[busy,setBusy]=useState(false),[error,setError]=useState(location.search.includes('error=')?'Sign-in was not completed. Use the approved owner account and try again.':'');return <main className="login"><Brand/><div className="login-body"><h1>Your clubs.<br/>One clear view.</h1><p>Check Secretary accounts, meeting boards and posting status in your private owner panel.</p><button disabled={busy} onClick={async()=>{setBusy(true);setError('');try{await signIn('google',{redirectTo:'/admin.html'});}catch{setError('Google sign-in could not start. Try again once owner login is configured.');setBusy(false);}}}>{busy?'Opening Google…':'Sign in with Google'}</button>{error&&<p role="alert" className="error">{error}</p>}<p className="quiet">Owner access only. Secretary conversations are not shown here.</p></div><a href="/">Back to the helper</a></main>;}
class Boundary extends React.Component{constructor(p){super(p);this.state={failed:false};}static getDerivedStateFromError(){return {failed:true};}render(){return this.state.failed?<main className="failure"><h1>This view is unavailable</h1><p>Your account may not have owner access, or the connection was interrupted. No club settings were changed.</p><button onClick={()=>location.reload()}>Try again</button><Exit/></main>:this.props.children;}}
function Exit(){const {signOut}=useAuthActions();return <button className="secondary" onClick={()=>signOut()}>Sign out</button>;}
function Activity({activity}){if(!activity)return <p className="quiet">Activity tracking has not started for this account.</p>;return <section className="activity-detail" aria-label="Account activity"><h3>Activity · last 7 days</h3><p className="quiet">Tracking since {date(activity.trackingSince)}. Earlier activity is unavailable.{!activity.complete?' Some records are missing; these counts are partial.':''}</p><dl className="settings"><div><dt>Last Secretary message</dt><dd>{date(activity.lastSecretaryAt)}</dd></div><div><dt>Last club activity</dt><dd>{date(activity.lastClubAt)}</dd></div>{[['Secretary messages',activity.secretaryMessages],['Member role requests',activity.memberReplies],['Confirmed role changes',activity.roleUpdates],['Boards approved',activity.boardsApproved],['Boards posted',activity.boardsPosted],['Delivery problems',activity.deliveryFailures],['Setups completed',activity.setupsCompleted]].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl></section>;}
function Usage({data,now}){const tracked=data.accounts.filter(a=>a.activity),active=new Set(tracked.filter(a=>a.activity.secretaryActive).map(a=>a.secretary)).size,clubs=tracked.filter(a=>a.activity.clubActive).length,service=data.health?.service,ai=data.health?.ai;const since=tracked.length?Math.min(...tracked.map(a=>a.activity.trackingSince)):null;return <section className="usage" aria-label="Usage and service status"><h2>Activity · last 7 days</h2><dl className="counts"><div><dt>Active Secretaries</dt><dd>{tracked.length?active:'—'}</dd></div><div><dt>Active clubs</dt><dd>{tracked.length?clubs:'—'}</dd></div></dl><p className="quiet">A Secretary is active after a private message to the helper. Club activity counts member role requests, role changes, approvals and posts.</p><p className="quiet">{since?`Tracking since ${date(since)}. Earlier activity is unavailable.`:'Waiting for activity tracking to start.'}{tracked.length<data.accounts.length?' Some accounts have no tracking data yet.':''}{tracked.some(a=>!a.activity.complete)?' Some counts are partial.':''}</p><details className="service-status"><summary>Helper status and shared AI limits</summary><dl className="settings"><div><dt>WhatsApp service</dt><dd>{!service?'Not available':now-service.lastCheckAt>60000?'Status delayed':service.connected?'Connected':'Disconnected'}</dd></div><div><dt>Last service check</dt><dd>{date(service?.lastCheckAt)}</dd></div><div><dt>AI calls · last hour</dt><dd>{ai?`${ai.callsLastHour} / ${ai.callLimit} · ${Math.max(0,ai.callLimit-ai.callsLastHour)} remaining`:'Not available'}</dd></div><div><dt>Shared budget safeguard</dt><dd>{ai?`$${ai.reservedUsd.toFixed(2)} reserved / $${ai.budgetLimitUsd.toFixed(2)} limit`:'Not available'}</dd></div></dl><p className="quiet">The budget safeguard is a shared estimate, not a bill or a cost for each Secretary.</p></details></section>;}
function Roles({rows}){return rows.length?<div className="table-scroll"><table><thead><tr><th scope="col">Role</th><th scope="col">Holder</th></tr></thead><tbody>{rows.map(r=><tr key={r.role}><td>{r.role}</td><td className={!r.member?'quiet':''}>{r.member||'Open'}</td></tr>)}</tbody></table></div>:<p className="quiet">No board saved yet.</p>;}
function Controls({account:a,health,now,stale}){
 const history=useQuery(api.admin.controlHistory,{clubId:a.id}),request=useMutation(api.admin.requestControl);
 const [confirm,setConfirm]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[waiting,setWaiting]=useState(null);
 const service=health?.service,ready=!stale&&service?.connected&&service.controlsCheckedAt&&now-service.controlsCheckedAt<120000;
 const pending=history?.find(r=>r.status==='pending'&&now-r.requestedAt<=300000);
 const result=waiting&&history?.find(r=>r.id===waiting.id);
 const syncing=waiting&&(!result||result.status==='pending'&&now-result.requestedAt<=300000||result.status==='succeeded'&&a.control?.token===waiting.expected);
 const disabled=busy||!!pending||!!syncing||!ready||!a.control||a.paused&&!!a.control.resumeBlocked||!history;
 const kind=a.paused?'resume':'pause',label=a.paused?'Resume':'Pause';
 return <section className="club-controls" aria-label="Club controls"><div className="control-heading"><h3>{a.paused?'Club paused':'Club running'}</h3><button className="secondary" disabled={disabled} onClick={()=>{setError('');setConfirm({kind,expected:a.control.token,club:a.club});}}>{label} this club</button></div>
 <p className="quiet">{a.paused?`Paused ${date(a.control?.pausedAt)}. ${a.control?.pauseReason||'Posting and reply processing are stopped.'}`:'Posting and role replies follow this club’s saved settings.'}</p>
 {!ready&&<p className="quiet">Controls are waiting for a fresh connection to the helper.</p>}
 {a.paused&&a.control?.resumeBlocked&&<p className="error">{a.control.resumeBlocked}</p>}
 {confirm&&<div className="control-confirm" role="group" aria-label={`${label} confirmation`}><h3>{confirm.kind==='pause'?'Pause':'Resume'} {confirm.club}?</h3><p>{confirm.kind==='pause'?'This stops automatic posts and processing replies for this club. Boards and drafts are saved. Other clubs keep running.':'This restarts this club using its saved board and schedule. Messages sent during the pause will not be processed. Approval rules still apply.'}</p><div className="control-buttons"><button disabled={disabled||a.control?.token!==confirm.expected} onClick={async()=>{setBusy(true);setError('');try{const id=await request({clubId:a.id,kind:confirm.kind,expected:confirm.expected,nonce:crypto.randomUUID()});setWaiting({id,expected:confirm.expected});setConfirm(null);}catch(e){setError(typeof e.data==='string'?e.data:'The request could not be sent. Refresh and try again.');}finally{setBusy(false);}}}>{busy?'Sending request…':`Confirm ${confirm.kind}`}</button><button className="secondary" disabled={busy} onClick={()=>setConfirm(null)}>Cancel</button></div>{a.control?.token!==confirm.expected&&<p className="error">The account changed. Cancel and check its latest status.</p>}</div>}
 {(pending||syncing)&&<p role="status">{result?.status==='succeeded'?'The helper confirmed the action. Waiting for the updated account…':'Waiting for the helper to confirm. This may take a few seconds.'}</p>}
 {error&&<p className="error" role="alert">{error}</p>}
 <details className="action-history"><summary>Owner action history</summary>{history?.length?<ul className="deliveries">{history.map(r=><li key={r.id}><span>{r.kind==='pause'?'Pause':'Resume'} · {r.status==='pending'&&now-r.requestedAt>300000?'Confirmation delayed · check the latest club status':r.status}<br/>{r.message}</span><time>{date(r.completedAt||r.requestedAt)}</time></li>)}</ul>:<p className="quiet">No owner actions recorded yet.</p>}</details></section>;
}
function Details({account:a,health,now,stale}){const [tab,setTab]=useState('current');useEffect(()=>setTab('current'),[a.id]);const shown=tab==='draft'?a.draft?.roles||[]:a[tab],m=tab==='draft'?a.draft?.meeting||a.meeting:a.meeting;return <section className="details" aria-label="Account details"><h2>{a.club}</h2><p className="quiet">Secretary +{a.secretary} · {a.group||'Group not connected'}</p><Controls account={a} health={health} now={now} stale={stale}/><dl className="settings"><div><dt>Meeting</dt><dd>{m.number||'Not set'} · {m.date||'Date not set'}</dd></div><div><dt>Time and venue</dt><dd>{m.time||'Not set'} · {m.venue||'Venue not set'}</dd></div><div><dt>Board updates</dt><dd>{a.postingTime||'Not set'} India time</dd></div><div><dt>Next pending update</dt><dd>{a.nextUpdate?date(a.nextUpdate):'No pending update'}</dd></div></dl><div className="board-tabs" aria-label="Choose a board">{[['current','Current roles'],['approved','Approved board'],['draft','Private draft']].map(([id,label])=><button className={tab===id?'selected':'secondary'} aria-pressed={tab===id} key={id} onClick={()=>setTab(id)}>{label}</button>)}</div><p className="board-note">{tab==='current'?'Latest saved roles, including confirmed member replies. Changes may still be awaiting approval or posting.':tab==='approved'?'The Secretary-approved board. Later member updates are shown under Current roles.':'Unapproved changes stay private until the Secretary approves.'}</p><Roles rows={shown}/><Activity activity={a.activity}/><h3>Recent delivery records</h3>{a.deliveries.length?<ul className="deliveries">{a.deliveries.slice().reverse().map((p,i)=><li key={i}><span>{p.status} · {p.acknowledged?'Delivery confirmed':'Delivery not confirmed'}</span><time>{date(p.postedAt)}</time></li>)}</ul>:<p className="quiet">No saved delivery records.</p>}</section>;}
function Overview(){const data=useQuery(api.admin.overview),[search,setSearch]=useState(''),[selected,setSelected]=useState(null),[now,setNow]=useState(Date.now());useEffect(()=>{const timer=setInterval(()=>setNow(Date.now()),30000);return ()=>clearInterval(timer);},[]);if(!data)return <main className="loading" role="status">Loading your Secretary accounts…</main>;const filtered=data.accounts.filter(a=>(a.club+' '+a.secretary+' '+(a.group||'')).toLowerCase().includes(search.toLowerCase()));const account=data.accounts.find(a=>a.id===selected);const stale=!data.capturedAt||now-data.capturedAt>180000;return <><header><Brand/><Exit/></header><main className="overview"><div className="heading"><div><h1>Secretary overview</h1><p>Check your clubs and the boards they are working on.</p></div><span className="read-only">Owner controls</span></div><p className={stale?'freshness stale':'freshness'} role="status">{data.capturedAt?`${stale?'Update delayed':'Last updated'}: ${date(data.capturedAt)} India time`:'Waiting for the first helper update. No account data has arrived yet.'}</p><dl className="counts">{[['Secretaries',data.count],['Connected clubs',data.connected],['Paused',data.paused],['Need attention',data.attention]].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{data.capturedAt?value:'—'}</dd></div>)}</dl><Usage data={data} now={now}/><label className="search">Find a Secretary or club<input type="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Club name or WhatsApp number"/></label><div className="workspace"><section aria-label="Secretary accounts" className="accounts">{filtered.length?filtered.map(a=><button className={'account '+(selected===a.id?'active':'')} key={a.id} onClick={()=>setSelected(a.id)}><span><strong>{a.club}</strong><small>+{a.secretary}</small><small>Secretary: {a.activity?.lastSecretaryAt?date(a.activity.lastSecretaryAt):a.activity?'No message since tracking began':'Activity unavailable'}</small></span><span className="status">{a.paused?'Paused':a.connected?'Connected':'Setup: '+a.stage.replaceAll('_',' ')}</span></button>):<p className="empty">{search?'No accounts match your search.':'No Secretary accounts yet.'}</p>}</section>{account?<Details key={account.id} account={account} health={data.health} now={now} stale={stale}/>:<section className="details empty"><h2>Select a club</h2><p>View its settings, all saved roles and recent delivery records.</p></section>}</div></main></>;}
function App(){const {isLoading,isAuthenticated}=useConvexAuth();return isLoading?<main className="loading" role="status">Checking your sign-in…</main>:isAuthenticated?<Boundary><Overview/></Boundary>:<Login/>;}
createRoot(document.getElementById('root')).render(<ConvexAuthProvider client={client}><App/></ConvexAuthProvider>);
